apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpass-secret
      mappingMethod: claim
      name: przem_htpasswd_provider
      type: HTPasswd
    - ldap:
        attributes:
          email: []
          id:
            - dn
            - mail
            - cn
          name:
            - cn
          preferredUsername:
            - uid
        bindDN: 'uid=przemyslaw.kuznicki,cn=users,cn=accounts,dc=lab,dc=internal'
        bindPassword:
          name: ldap-secret
        insecure: true
        url: 'ldap://idm.lab.internal/cn=accounts,dc=lab,dc=internal?uid'
      mappingMethod: claim
      name: przem_ldap_provider
      type: LDAP
